### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by mbasaglia** [mbasaglia/Melanobot_v2#8]
Add a list to handle todo lists
- [ ] A user has access to their own lists
- [ ] Admins can access any list
- [ ] Add new entries `Bot: todo (list) add something`
- [ ] Display entries `Bot: todo (list)`
- [ ] Remove entries `Bot: todo (list) rm #2|something`
- [ ] Automatic topic `Bot: todo topic Stuff to do: %`
